site_name: Naoki Ito
theme: mkdocs
pages:
  - CV: 'index.md'
  - In Japan: 'achievement-ja.md'
extra_css:
    # - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    # - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "custom.css"

